[book]
authors = [ "Zonemaster Team" ]
description = "Zonemaster documentation"
language = "en"
src = "./"

[output.html]
no-section-label = true

[output.html.fold]
enable = true
level = 1

[preprocessor.index]
